# Site setings
name: 'Horace'
description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
# disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Richard Hewitt'
  image: 'authorimage.jpg'
  greetings: 'Rich Hewitt'
  description: "Hey there! I'm an experience Product Owner and Scrum Master known for moving fast and getting things done.  Current focus is on web3.  Reach out to me on social media or email(at)richhewitt.com"
  bio: ''

# Contact form setings
email: email@richhewitt.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. I will reply soon!"

# Social links
twitter: 'hewittjustdoit'
facebook: 'richhewitt'
github: 'richhewitt'
instagram: 'richardlhewitt'
linkedin: 'richhewitt'

# Navigation
# navigation:
#  - text: About
#    url: /about/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
