# Site setings
name: ''
description: ''
meta_description: 'The personal website of Rich Hewitt'
# logo: ''
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://richhewitt.com/
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Richard Hewitt'
  image: 'authorimage.jpg'
  greetings: 'Rich Hewitt'
  description: "Hey there! I'm a Product Manager with 8 years experience, known for moving fast and getting things done.  Shoot me a message anytime."
  bio: ''

# Contact form setings
email:
contact_page_description: ""
thankyou_page_description: ""

# Social links
email: 'email@richhewitt.com'
github: 'richhewitt'
linkedin: 'richhewitt'
twitter: 'thebitcoinrich'

# Navigation
# navigation:
#  - text: About
#    url: /about/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
